name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Rename extensionless files for Sonar
        run: |
          mv bin/inspect-pid bin/inspect-pid.sh
          mv bin/procscan bin/procscan.py

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=Solvro_devops-utils_9dffb7f7-87e9-43df-9b03-ec0e8d0dcb76
            -Dsonar.sources=.
            -Dsonar.exclusions=**/build/**,**/dist/**,**/tests/**,**/.terraform/**,**/target/**
